FROM node:6.2-slim

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ENV NODE_ENV development

COPY package.json /usr/src/app/
RUN npm install
RUN npm install -g nodemon
COPY . /usr/src/app

ENV PORT 80
EXPOSE 80
